version: '2'

services:
  fullstack-app:
    ports:
    - 127.0.0.1:3000:3000/tcp
    environment:
      MONGODB_URI: mongodb://192.168.8.114:27017/fullstackapp
    networks:
      - fullstackapp-network
    tty: true
    image: fullstackapp
    stdin_open: true
    container_name: fullstackapp
networks:
  fullstackapp-network:
    driver: bridge
